version: '2'
services:

    # The Application
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "host=localhost"

    # The Web Server
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        links:
            - app
        ports:
            - 8091:80

    # The Database
    database:
        image: mysql:5.7
        volumes:
            - db:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=true"
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=laravel"
            - "MYSQL_PASSWORD=laravel"
        ports:
            - "33062:3306"

volumes:
    db:
